// console.log(data.tracks.items[0]);

{
    album: {
        album_type: 'compilation',
        artists: [
            [Object]
        ],
        available_markets: ['AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
        ],
        external_urls: {
            spotify: 'https://open.spotify.com/album/5HY7d62IQ9p4snnM1d8qLM'
        },
        href: 'https://api.spotify.com/v1/albums/5HY7d62IQ9p4snnM1d8qLM',
        id: '5HY7d62IQ9p4snnM1d8qLM',
        images: [
            [Object],
            [Object],
            [Object]
        ],
        name: 'The Greatest Hits Collection (Collector Edition)',
        release_date: '2017-11-24',
        release_date_precision: 'day',
        total_tracks: 32,
        type: 'album',
        uri: 'spotify:album:5HY7d62IQ9p4snnM1d8qLM'
    },
    artists: [{
        external_urls: [Object],
        href: 'https://api.spotify.com/v1/artists/3sc7iUG1Wwpwx7bHeZolgx',
        id: '3sc7iUG1Wwpwx7bHeZolgx',
        name: 'Bananarama',
        type: 'artist',
        uri: 'spotify:artist:3sc7iUG1Wwpwx7bHeZolgx'
    }],
    available_markets: ['AD',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IS',
        'IT',
        'JP',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'RO',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA'
    ],
    disc_number: 1,
    duration_ms: 215400,
    explicit: false,
    external_ids: {
        isrc: 'GBAAP9500222'
    },
    external_urls: {
        spotify: 'https://open.spotify.com/track/0wnJdLDUi9fkDl5nxhDlqO'
    },
    href: 'https://api.spotify.com/v1/tracks/0wnJdLDUi9fkDl5nxhDlqO',
    id: '0wnJdLDUi9fkDl5nxhDlqO',
    is_local: false,
    name: 'Cruel Summer',
    popularity: 60,
    preview_url: 'https://p.scdn.co/mp3-preview/a6b3f58b1c94d2e14ec7f95eb7970bf87fbf2d5d?cid=81102095a43e49f89cd3ba99822f6c89',
    track_number: 11,
    type: 'track',
    uri: 'spotify:track:0wnJdLDUi9fkDl5nxhDlqO'
}